import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

import { Product } from '../models/product.model';

const products = [
  // ── Earrings ──
  {
    name: 'Sunflower Earrings',
    description: 'Bright and cheerful sunflower earrings that bring a touch of sunshine to any outfit.',
    longDescription: 'These handcrafted sunflower earrings are made with care and attention to detail. Each pair features a vibrant sunflower design that adds a pop of color and positivity to your everyday look. Perfect for school, casual outings, or gifting to a friend who loves nature-inspired jewelry.',
    price: 8.00,
    images: ['/products/sunflower-earrings.jpg'],
    category: 'earrings',
    featured: true,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 20,
  },
  {
    name: 'Cactus Earrings',
    description: 'Adorable cactus-shaped earrings for a fun, desert-inspired look.',
    longDescription: 'Show off your love for all things cute and quirky with these cactus earrings. Made with high-quality materials, these earrings are lightweight and comfortable for all-day wear. A perfect accessory for plant lovers and anyone who appreciates unique jewelry designs.',
    price: 9.00,
    images: ['/products/cactus-earrings.jpg'],
    category: 'earrings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Ice Cream Cone Earrings',
    description: 'Sweet ice cream cone earrings that are perfect for summer vibes.',
    longDescription: 'Treat yourself to these delightful ice cream cone earrings! These playful earrings feature a detailed ice cream cone design that is sure to spark joy. Lightweight and durable, they are ideal for everyday wear or as a fun gift for someone special.',
    price: 9.00,
    images: ['/products/ice-cream-cone-earrings.jpg'],
    category: 'earrings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Paint Palette Earrings',
    description: 'Colorful paint palette earrings for the creative soul.',
    longDescription: 'Express your artistic side with these charming paint palette earrings. Each pair features a miniature paint palette design with colorful details. Perfect for art lovers, students, and anyone who wants to add a creative touch to their jewelry collection.',
    price: 9.00,
    images: ['/products/paint-palette-earrings.jpg'],
    category: 'earrings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Rose Quartz Heart Earrings',
    description: 'Elegant rose quartz heart earrings symbolizing love and compassion.',
    longDescription: 'These stunning rose quartz heart earrings bring a touch of elegance and meaning to your jewelry collection. Rose quartz is known as the stone of love, making these earrings the perfect gift for someone special or a beautiful treat for yourself.',
    price: 10.00,
    images: ['/products/rose-quartz-heart-earrings.jpg'],
    category: 'earrings',
    featured: true,
    new: false,
    options: { materials: ['Silver', 'Rose Quartz'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 0,
  },
  {
    name: 'Rose Earrings',
    description: 'Delicate rose-shaped earrings for a timeless, romantic look.',
    longDescription: 'Add a touch of romance to your style with these beautiful rose earrings. Featuring a classic rose design, these earrings are both elegant and affordable. Perfect for everyday wear or special occasions.',
    price: 4.00,
    images: ['/products/rose-earrings.jpg'],
    category: 'earrings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 25,
  },
  {
    name: 'Pineapple Earrings',
    description: 'Tropical pineapple earrings that add a fun flair to any outfit.',
    longDescription: 'Bring the tropics to your everyday look with these adorable pineapple earrings. These lightweight earrings feature a detailed pineapple design and are perfect for summer, vacations, or whenever you want to add a splash of fun to your accessories.',
    price: 8.00,
    images: ['/products/pineapple-earrings.jpg'],
    category: 'earrings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 0,
  },
  {
    name: 'Leaf Earrings',
    description: 'Nature-inspired leaf earrings with a minimalist design.',
    longDescription: 'These elegant leaf earrings bring a touch of nature to your jewelry collection. Featuring a delicate leaf design, they are perfect for anyone who loves minimalist, nature-inspired accessories. Lightweight and comfortable for all-day wear.',
    price: 8.00,
    images: ['/products/leaf-earrings.jpg'],
    category: 'earrings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 20,
  },

  // ── Charms ──
  {
    name: 'Zodiac Sign Charms',
    description: 'Personalized zodiac sign charms — choose your star sign!',
    longDescription: 'Find your zodiac sign and wear it proudly with these beautiful zodiac charms. Available in all 12 signs, these charms make a thoughtful and personalized gift. Add them to a chain or bracelet for a custom look that is uniquely yours.',
    price: 2.00,
    images: ['/products/zodiac-sign-charms.jpg'],
    category: 'charms',
    featured: true,
    new: false,
    options: { materials: ['Silver'], customization: ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'] },
    reviews: [],
    relatedProducts: [],
    stock: 50,
  },
  {
    name: 'Giving Tree Charm',
    description: 'A meaningful giving tree charm inspired by the classic story.',
    longDescription: 'This charming giving tree charm is inspired by the beloved children\'s book. A beautiful reminder of generosity and love, it makes a meaningful gift for readers, teachers, and anyone who appreciates timeless stories.',
    price: 2.00,
    images: ['/products/giving-tree-charm.jpg'],
    category: 'charms',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 30,
  },
  {
    name: 'Alphabet Charms',
    description: 'Personalized alphabet charms — choose your initial!',
    longDescription: 'Make it personal with these alphabet charms. Available in every letter, these charms are perfect for customizing necklaces, bracelets, or keychains. A great gift idea for friends, family, or yourself.',
    price: 2.00,
    images: ['/products/alphabet-charms.jpg'],
    category: 'charms',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'] },
    reviews: [],
    relatedProducts: [],
    stock: 50,
  },
  {
    name: 'Heart Locket Charm',
    description: 'A sweet heart locket charm that opens to hold a tiny treasure.',
    longDescription: 'This adorable heart locket charm opens up so you can place a tiny photo or keepsake inside. Made with attention to detail, it\'s the perfect sentimental gift or a lovely addition to your own charm collection.',
    price: 2.00,
    images: ['/products/heart-locket-charm.jpg'],
    category: 'charms',
    featured: false,
    new: true,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 25,
  },
  {
    name: 'Birthstone Charms',
    description: 'Sparkly birthstone charms — pick your birth month!',
    longDescription: 'Celebrate your birthday month with these beautiful birthstone charms. Available in all 12 months, each charm features a sparkling stone in your birth color. Perfect as a personalized gift or a colorful addition to any jewelry piece.',
    price: 2.00,
    images: ['/products/birthstone-charms.jpg'],
    category: 'charms',
    featured: true,
    new: false,
    options: { materials: ['Silver'], customization: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] },
    reviews: [],
    relatedProducts: [],
    stock: 50,
  },
  {
    name: 'Positive Word Charm: Enjoy Everyday',
    description: 'An inspirational charm with the message "Enjoy Everyday".',
    longDescription: 'Carry positivity with you wherever you go with this inspirational word charm. Engraved with "Enjoy Everyday," it serves as a daily reminder to appreciate the little things. Add it to a chain or bracelet for a meaningful accessory.',
    price: 2.00,
    images: ['/products/positive-word-enjoy-everyday.jpg'],
    category: 'charms',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 30,
  },
  {
    name: 'Positive Word Charm: Yay!',
    description: 'A cheerful charm engraved with "Yay!" to brighten your day.',
    longDescription: 'Spread joy and positivity with this fun "Yay!" charm. Perfect for celebrating small wins and big moments alike. Attach it to your favorite chain or bracelet for a dose of happiness every day.',
    price: 2.00,
    images: ['/products/positive-word-yay.jpg'],
    category: 'charms',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 30,
  },
  {
    name: 'Positive Word Charm: You Got This!',
    description: 'An encouraging charm with the message "You Got This!"',
    longDescription: 'Need a little encouragement? This "You Got This!" charm is the perfect pick-me-up. Wear it as a reminder that you can handle anything that comes your way. Makes a wonderful motivational gift for friends and loved ones.',
    price: 2.00,
    images: ['/products/positive-word-you-got-this.jpg'],
    category: 'charms',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 30,
  },

  // ── Chains ──
  {
    name: 'Silver Thin Curb Chain',
    description: 'A classic thin curb chain in silver — sold per inch.',
    longDescription: 'This silver thin curb chain is a versatile staple for any jewelry collection. Its delicate design makes it perfect for pairing with charms or wearing on its own. Sold per inch so you can customize the length to your preference.',
    price: 0.30,
    images: ['/products/thin-curb-chain.jpg'],
    category: 'chains',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 100,
  },
  {
    name: 'Silver Thin Twisted Curb Chain',
    description: 'A twisted curb chain with a unique, eye-catching design.',
    longDescription: 'Add a twist to your look with this silver thin twisted curb chain. The twisted links catch the light beautifully, creating a subtle sparkle. Perfect for layering or wearing solo with your favorite charm.',
    price: 0.30,
    images: ['/products/thin-twisted-curb-chain.jpg'],
    category: 'chains',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 100,
  },
  {
    name: 'Silver Thin Cable Chain',
    description: 'A simple and elegant thin cable chain in silver.',
    longDescription: 'This classic silver thin cable chain features uniform round links for a clean, timeless look. Lightweight and comfortable, it\'s perfect for everyday wear and pairs beautifully with pendants and charms.',
    price: 0.24,
    images: ['/products/thin-cable-chain.jpg'],
    category: 'chains',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 100,
  },
  {
    name: 'Silver Thin Trace Chain',
    description: 'A delicate trace chain for a refined, minimal look.',
    longDescription: 'The silver thin trace chain offers a refined and minimal look that complements any pendant or charm. Its fine links create an elegant appearance that is perfect for both casual and dressy occasions.',
    price: 0.24,
    images: ['/products/thin-trace-chain.jpg'],
    category: 'chains',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 100,
  },
  {
    name: 'Silver Pelline Ball Chain',
    description: 'A playful pelline ball chain with small spherical links.',
    longDescription: 'This silver pelline ball chain features small, evenly spaced spherical links for a unique and playful look. It\'s a fun alternative to traditional chain styles and works great with charms and pendants.',
    price: 0.25,
    images: ['/products/pelline-ball-chain.jpg'],
    category: 'chains',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 100,
  },
  {
    name: 'Silver Thick Cable Trace Chain',
    description: 'A thicker cable trace chain for a bolder statement.',
    longDescription: 'Make a statement with this silver thick cable trace chain. Its slightly larger links provide a bolder look while still maintaining elegance. A best-seller that pairs perfectly with larger charms and pendants.',
    price: 0.32,
    images: ['/products/thick-cable-trace-chain.jpg'],
    category: 'chains',
    featured: true,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 100,
  },
  {
    name: 'Silver Round Twisted Trace Chain',
    description: 'A round twisted trace chain with beautiful light-catching links.',
    longDescription: 'This silver round twisted trace chain features twisted links that catch the light from every angle. Its unique design adds texture and interest to any jewelry look. Perfect for layering with other chains.',
    price: 0.28,
    images: ['/products/round-twisted-trace-chain.jpg'],
    category: 'chains',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 100,
  },
  {
    name: 'Silver Slender Cable Chain',
    description: 'An ultra-fine slender cable chain for a dainty look.',
    longDescription: 'This ultra-fine silver slender cable chain is perfect for those who love dainty, minimalist jewelry. Its slender links create a barely-there look that is elegant and sophisticated.',
    price: 0.28,
    images: ['/products/slender-cable-chain.jpg'],
    category: 'chains',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 0,
  },

  // ── Rings ──
  {
    name: 'Silver Curb Chain Ring',
    description: 'A trendy curb chain ring in silver.',
    longDescription: 'This silver curb chain ring combines the classic chain link design with a modern ring silhouette. Its bold, trendy look makes it a standout piece that can be worn alone or stacked with other rings.',
    price: 4.00,
    images: ['/products/silver-curb-chain-ring.jpg'],
    category: 'rings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Gold Curb Chain Ring',
    description: 'A trendy curb chain ring in gold.',
    longDescription: 'Elevate your ring game with this gold curb chain ring. The warm gold tone adds a luxurious touch to the popular chain link design. Perfect for everyday wear or as a statement piece.',
    price: 5.00,
    images: ['/products/gold-curb-chain-ring.jpg'],
    category: 'rings',
    featured: false,
    new: false,
    options: { materials: ['Gold'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Silver Middle-Diamond-Stone Ring (Double-Band)',
    description: 'An elegant silver double-band ring with a center diamond stone.',
    longDescription: 'This elegant silver ring features a sparkling center diamond stone set between two delicate bands. The double-band design adds depth and sophistication, making it a beautiful choice for special occasions or everyday elegance.',
    price: 4.00,
    images: ['/products/silver-diamond-ring-double.jpg'],
    category: 'rings',
    featured: true,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Gold Middle-Diamond-Stone Ring (Double-Band)',
    description: 'An elegant gold double-band ring with a center diamond stone.',
    longDescription: 'This stunning gold ring features a brilliant center diamond stone framed by two graceful bands. The gold finish adds warmth and luxury to this timeless design. Perfect as a gift or a treat for yourself.',
    price: 5.00,
    images: ['/products/gold-diamond-ring-double.jpg'],
    category: 'rings',
    featured: false,
    new: false,
    options: { materials: ['Gold'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 0,
  },
  {
    name: 'Silver Middle-Diamond-Stone Ring (Single-Band)',
    description: 'A sleek silver single-band ring with a center diamond stone.',
    longDescription: 'Simple yet stunning, this silver single-band ring features a sparkling center diamond stone. Its minimalist design makes it a versatile piece that pairs well with other rings or shines beautifully on its own.',
    price: 3.00,
    images: ['/products/silver-diamond-ring-single.jpg'],
    category: 'rings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Gold Middle-Diamond-Stone Ring (Single-Band)',
    description: 'A sleek gold single-band ring with a center diamond stone.',
    longDescription: 'This beautiful gold single-band ring features a dazzling center diamond stone set in a warm gold band. Its elegant simplicity makes it perfect for stacking or wearing as a standalone statement piece.',
    price: 4.00,
    images: ['/products/gold-diamond-ring-single.jpg'],
    category: 'rings',
    featured: false,
    new: false,
    options: { materials: ['Gold'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 0,
  },
  {
    name: 'Silver Bow Ring',
    description: 'A charming silver bow ring for a cute, feminine look.',
    longDescription: 'This adorable silver bow ring features a beautifully crafted bow design that adds a touch of charm and femininity to any outfit. Lightweight and comfortable, it\'s a sweet everyday accessory.',
    price: 4.00,
    images: ['/products/silver-bow-ring.jpg'],
    category: 'rings',
    featured: false,
    new: false,
    options: { materials: ['Silver'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
  {
    name: 'Gold Bow Ring',
    description: 'A charming gold bow ring for a cute, feminine look.',
    longDescription: 'Add a touch of elegance with this gold bow ring. The bow design is both playful and sophisticated, making it a versatile piece that transitions easily from day to night. A lovely gift for any occasion.',
    price: 5.00,
    images: ['/products/gold-bow-ring.jpg'],
    category: 'rings',
    featured: false,
    new: false,
    options: { materials: ['Gold'], customization: [] },
    reviews: [],
    relatedProducts: [],
    stock: 15,
  },
];

async function seed() {
  const MONGODB_URI = process.env.MONGODB_URI;
  if (!MONGODB_URI) {
    console.error('MONGODB_URI is not set in .env');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  const existing = await Product.countDocuments();
  if (existing > 0) {
    console.log(`Database already has ${existing} products. Clearing and re-seeding...`);
    await Product.deleteMany({});
  }

  const inserted = await Product.insertMany(products);
  console.log(`Seeded ${inserted.length} products successfully.`);

  for (const p of inserted) {
    console.log(`  [${p.category}] ${p.name} - $${p.price} (stock: ${p.stock})`);
  }

  await mongoose.disconnect();
  console.log('Done.');
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
